### ISSUE TITLE
crash loop after upgrade k8s to v1.30.4+rke2r1

### ISSUE THREAD

**Issue by kissi7** [openshift/ovirt-csi-driver#140]
ovirt csi driver is in crashloop after upgrade of kubernetes cluster to v1.30.4+rke2r1

```
panic: flag logtostderr set at /src/ovirt-csi-driver/cmd/ovirt-csi-driver/ovirt-csi-driver.go:29 before being defined
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000f8000, {0x20c5070, 0x2f4eee0}, {0x1e23c8f, 0xb}, {0x1e504c0, 0x26})
	/usr/lib/golang/src/flag/flag.go:1031 +0x314
flag.(*FlagSet).BoolVar(...)
	/usr/lib/golang/src/flag/flag.go:749
k8s.io/klog.InitFlags(0xc0000f8000?)
	/src/ovirt-csi-driver/vendor/k8s.io/klog/klog.go:425 +0xe9
main.init.0()
	/src/ovirt-csi-driver/cmd/ovirt-csi-driver/ovirt-csi-driver.go:30 +0x3f
```

**Comment by J-Ha** [comment]
hej im facing the same issue, maybe someone could take a look
cc @engelmi @eslutsky
